// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6UPQfqWUxJkNC5Wo8N00MtO1lCxqlDpo',
    appId: '1:869235854239:web:d963d5fad547f1c734cbaa',
    messagingSenderId: '869235854239',
    projectId: 'database-glupulse',
    authDomain: 'database-glupulse.firebaseapp.com',
    storageBucket: 'database-glupulse.firebasestorage.app',
    measurementId: 'G-0PKQ73Z5W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuX4znedhqH1C8NQ6jKcbOycpbSSw-9EY',
    appId: '1:869235854239:android:ef136618716de50134cbaa',
    messagingSenderId: '869235854239',
    projectId: 'database-glupulse',
    storageBucket: 'database-glupulse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB81caWFYvi_NRGm7WB2aTJXZh-xzR15MY',
    appId: '1:869235854239:ios:dff832e1ffadd13434cbaa',
    messagingSenderId: '869235854239',
    projectId: 'database-glupulse',
    storageBucket: 'database-glupulse.firebasestorage.app',
    iosBundleId: 'com.example.finpro',
  );
}
